language: python

python:
  - "3.3"
  - "3.4"

cache:
  directories:
  - build

before_install:
  - mkdir -p build
  - sudo apt-get install -qqm wget build-essential python3-dev
  - sudo apt-get install -qqm python3-pyqt4 python3-sip-dev
  # install SIP
  - cd build
  - wget --quiet --output-document=sip.tar.gz http://downloads.sourceforge.net/project/pyqt/sip/sip-4.15.3/sip-4.15.3.tar.gz
  - tar -xf sip.tar.gz
  - cd sip-4.15.3
  - python -B configure.py
  - make
  - sudo make install
  # install PyQt
  - cd $TRAVIS_BUILD_DIR/build
  - wget --quiet --output-document=pyqt.tar.gz http://downloads.sourceforge.net/project/pyqt/PyQt4/PyQt-4.10.3/PyQt-x11-gpl-4.10.3.tar.gz
  - tar -xf pyqt.tar.gz
  - cd PyQt-x11-gpl-4.10.3
  - python -B configure.py --confirm-license
  - make
  - sudo make install
  - python -c 'import PyQt4'  # Check if it's ok
  - cd $TRAVIS_BUILD_DIR

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#gns3"
    on_success: change
    on_failure: always

install:
  - "pip install -r dev-requirements.txt"

script: "xvfb-run py.test --verbose" # Run tests in a fake X server


